# Generated by Django 4.1.1 on 2022-10-04 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='age',
        ),
        migrations.AddField(
            model_name='work',
            name='job',
            field=models.CharField(default=django.utils.timezone.now, max_length=600, verbose_name='Job'),
            preserve_default=False,
        ),
    ]
